apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
          - name: http_proxy
            value: "http://47.104.224.148:30001"
          - name: https_proxy
            value: "http://47.104.224.148:30001"
          - name: USE_ISTIO
            value: $(USE_ISTIO)
          - name: ISTIO_GATEWAY
            value: $(ISTIO_GATEWAY)
